spring:
  application:
    name: topApi_service_push
  redis:
    host: localhost
    password:
    port: 6379

server:
  port: 8081

socket:
  hostname: localhost
  hostPort: 8082
  urlParam: account

rocketmq:
  name-server: 192.168.50.195:9876
  consumer:
    group: topinfura255
    sendMessageTimeout: 300000
  producer:
    group: topinfura255
    send-message-timeout: 3000

ws:
  rocketmq:
    topic: test
    topic_block: topic_new_unitblock
    topic_transaction: topic_new_transaction
    topic_account: topic_new_account